image: maven:3.6.3-jdk-11

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    maven: ~/.m2/repository
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
    
# Workflow Configuration

pipelines:
  default:
      - step:
          name: build-test-sonar
          caches:
            - maven
            - sonar
          script:
            - mvn -B verify sonar:sonar
      - step:
          name: deploy
          caches:
            - maven
          script:
            - mvn -s https://zoostar.jfrog.io/artifactory/maven-quickstart-local/settings.xml deploy